services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
      - ./custom_pg_hba.conf:/etc/postgresql/custom_pg_hba.conf:ro
      - postgres-data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      # Optional: To enforce SSL connections, you might also need to
      # mount a custom pg_hba.conf and set hba_file
      - "-c"
      - "hba_file=/etc/postgresql/custom_pg_hba.conf"
    ports:
      - 5432:5432
    healthcheck:
      # This test ensures that Electric only attempts to connect once Postgres is fully ready.
      # It uses the standard pg_isready utility to check the database connection status.
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - electric-net

  cert-renewer:
    image: postgres:17.5-bookworm
    container_name: postgres-cert-renewer
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ssl-renew.sh:/usr/local/bin/ssl-renew.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - POSTGRES_CONTAINER=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    entrypoint: >
      sh -c "
        apt-get update && apt-get install -y cron docker.io &&
        chmod +x /usr/local/bin/ssl-renew.sh &&
        echo '*/2 * * * * /usr/local/bin/ssl-renew.sh >> /var/log/ssl-renew.log 2>&1' | crontab - &&
        cron -f
      "
    depends_on:
      - postgres
    networks:
      - electric-net

  electric:
    image: electricsql/electric:1.0.20
    container_name: electric
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL} # This URL must use the service name 'postgres' as the host
      ELECTRIC_SECRET: ${ELECTRIC_SECRET}
    # ports:
    #   - 3000:3000 # IMPORTANT: Do not expose the Electric port outside the network, use caddy as a reverse proxy instead
    networks:
      - electric-net

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    # It is good practice to also give your custom-built image a name.
    # This makes it easier to manage and inspect.
    image: caddy-proxy-with-jwt:latest
    container_name: caddy
    depends_on:
      - electric
    environment:
      ELECTRIC_URL: ${ELECTRIC_URL}
      ELECTRIC_SECRET: ${ELECTRIC_SECRET}
      AUTH_SECRET_BASE64: ${AUTH_SECRET_BASE64}
      CORS_ORIGIN: ${CORS_ORIGIN}
      PROXY_HOST: ${PROXY_HOST}
      PROXY_PORT: ${PROXY_PORT}
    ports:
      # - "80:80"
      # - "443:443"
      # - "443:443/udp" # For HTTP/3
      # - "8080:8080" # For local development
      - "8443:8443" # For local development with HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Mounts your custom Caddyfile
      - ./caddy-certs:/data/caddy/pki/authorities/local # TLS certificates
      - caddy-data:/data                 # Persists Caddy's data like TLS certificates
      - caddy-config:/config             # Persists Caddy's configuration
    networks:
      - electric-net

volumes:
  postgres-data:
  caddy-data:
  caddy-config:

networks:
  electric-net:
    driver: bridge